# Generated by Django 4.1.13 on 2023-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(default="", upload_to="images"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(default="", upload_to="videos"),
        ),
    ]
