# Generated by Django 4.1.13 on 2023-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multimedia", "0002_alter_image_image_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(default="assets\\image.png", upload_to="images"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                default="multimedia_site/media/assets/video.mp4", upload_to="videos"
            ),
        ),
    ]
