# Generated by Django 4.1.13 on 2023-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multimedia", "0005_video_video_link_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
